name: CI Security Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sast:
    name: Static Code Analysis (SAST)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Run CodeQL (SAST)
        uses: github/codeql-action/init@v2
        with:
          languages: javascript  # Değiştirilebilir
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  dependencies:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "MyApp"
          scanPath: .
          format: "HTML"
          out: "reports"

      - name: Upload Dependency Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports

  container_scan:
    name: Container Image Scan
    runs-on: ubuntu-latest
    needs: [sast, dependencies]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t myapp:latest .

      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myapp:latest
          format: table
          exit-code: 0  # Hatalarda bile durdurmaz
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  dast:
    name: Dynamic App Security Test (DAST)
    runs-on: ubuntu-latest
    needs: container_scan
    steps:
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'http://localhost:3000'  # Değiştir