import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

import { createLogger, format, transports } from 'winston';
import Script from 'next/script';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			{/* <Script
				src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
				integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
				crossOrigin="anonymous"
				referrerPolicy="no-referrer"
			></Script> */}
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				{children}
			</body>

			{/* SubResource Integrity SRI */}
		</html>
	);
}
